### ISSUE TITLE
Bot signup prevention

### ISSUE THREAD

**Issue by truvatech** [freshbrewedweb/asgard#88]
Our mailing list just grew by like 10k in the past week... what the hell is going on?

Any chance we could limit bot signups somehow?

Thanks

**Comment by greghunt** [comment]
Is this better now?

**Comment by truvatech** [comment]
Not really sure. Mad mimi sucks and doesn't give us analytics. Can't really
track user base growth as well as we could with mailchimp

I'll keep an eye out though

*Yannick Richard*
about.me/yannickrichard
www.ymrtech.com
1-(844) 262-7900 and press 9
